services:
  - type: web
    name: order-tracker
    env: static
    buildCommand: npm install
    staticPublishPath: .
    routes:
      - type: rewrite
        source: /*
        destination: /index.html